import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { Icon, LinkedRecord, PrimaryButton, SectionTitle, SeverityPill, Surface } from "@/components/atlas-ui";
import { ScreenContainer } from "@/components/screen-container";
import { agentFindings } from "@/lib/atlas-advanced";

const iconFor = (agent: string) => agent === "asset" ? "precision-manufacturing" : agent === "supply" ? "inventory-2" : agent === "logistics" ? "local-shipping" : agent === "finance" ? "account-balance" : "engineering" as const;
const severityFor = (state: string) => state === "at_risk" ? "high" : state === "watch" ? "attention" : "good" as const;
export default function AgentsScreen() { return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.header}><View style={styles.icon}><Icon name="smart-toy" color="#21D4C2" size={21} /></View><View><Text style={styles.eyebrow}>Shared enterprise context</Text><Text style={styles.title}>Agent coordination</Text></View></View>
  <Surface style={styles.summary}><Text style={styles.summaryLabel}>ONE COHERENT RECOMMENDATION</Text><Text style={styles.summaryTitle}>Protect the SO-812 delivery path while preserving safe recovery capacity.</Text><Text style={styles.summaryBody}>Operations, asset, supply, logistics, and finance findings are presented together; no agent may independently execute a material operational action.</Text><PrimaryButton label="Review recovery scenario" icon="account-tree" onPress={() => router.push("/scenario")} /></Surface>
  <SectionTitle eyebrow="Specialist findings" title="Shared context" />
  <View style={styles.records}>{agentFindings.map((finding) => <LinkedRecord key={finding.agent} icon={iconFor(finding.agent)} title={`${finding.agent} agent · ${finding.title}`} detail={`${finding.finding} · ${finding.evidenceState}`} severity={severityFor(finding.riskState)} />)}</View>
  <SectionTitle eyebrow="Coordination protocol" title="Human control" /><Surface style={styles.protocol}><Step index="1" title="Observe" text="Agents consume the same facility-scoped events, records, and operating state." /><Step index="2" title="Interpret" text="Each finding carries a verified, likely, estimated, or unknown evidence label." /><Step index="3" title="Authorize" text="Atlas routes a combined recommendation to the approval policy before workflow execution." /></Surface><View style={{ height: 28 }} />
</ScrollView></ScreenContainer>; }
function Step({ index, title, text }: { index: string; title: string; text: string }) { return <View style={styles.step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{index}</Text></View><View style={{ flex: 1 }}><Text style={styles.stepTitle}>{title}</Text><Text style={styles.stepText}>{text}</Text></View></View>; }
const styles = StyleSheet.create({ content: { gap: 15, paddingHorizontal: 18, paddingTop: 10 }, header: { alignItems: "center", flexDirection: "row", gap: 10 }, icon: { alignItems: "center", backgroundColor: "#183536", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, eyebrow: { color: "#8EA0A7", fontSize: 10, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, title: { color: "#E8F0F1", fontSize: 29, fontWeight: "900", letterSpacing: -0.9 }, summary: { gap: 10, padding: 15 }, summaryLabel: { color: "#21D4C2", fontSize: 10, fontWeight: "900", letterSpacing: 0.9 }, summaryTitle: { color: "#E5EFF0", fontSize: 17, fontWeight: "900", lineHeight: 22 }, summaryBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18 }, records: { gap: 9 }, protocol: { gap: 13, padding: 15 }, step: { alignItems: "flex-start", flexDirection: "row", gap: 10 }, stepNumber: { alignItems: "center", backgroundColor: "#1B4543", borderRadius: 13, height: 26, justifyContent: "center", width: 26 }, stepNumberText: { color: "#75E8DA", fontSize: 12, fontWeight: "900" }, stepTitle: { color: "#DCE8EA", fontSize: 13, fontWeight: "800" }, stepText: { color: "#9FB2B7", fontSize: 11, lineHeight: 16, marginTop: 3 } });
