import { ScrollView, StyleSheet, Text, View } from "react-native";

import { Icon, SectionTitle, SeverityPill, Surface } from "@/components/atlas-ui";
import { ScreenContainer } from "@/components/screen-container";
import { approvalPolicies } from "@/lib/atlas-advanced";

const severityFor = (risk: string) => risk === "critical" ? "critical" : risk === "high" ? "high" : risk === "medium" ? "attention" : "good" as const;
export default function GovernanceScreen() { return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.header}><View style={styles.icon}><Icon name="gpp-good" color="#21D4C2" size={21} /></View><View><Text style={styles.eyebrow}>Industrial governance center</Text><Text style={styles.title}>Control plane</Text></View></View>
  <Surface style={styles.headerCard}><Text style={styles.headerTitle}>Policies turn approved intent into bounded action.</Text><Text style={styles.headerBody}>Atlas keeps deterministic rules, role requirements, AI recommendations, audit records, and verification separate so automation remains explainable and reversible.</Text></Surface>
  <SectionTitle eyebrow="Approval graph" title="Active policies" />
  <View style={styles.policies}>{approvalPolicies.map((policy) => <Surface key={policy.id} style={styles.policy}><View style={styles.policyTop}><View style={{ flex: 1 }}><Text style={styles.policyTitle}>{policy.title}</Text><Text style={styles.policyId}>{policy.id}</Text></View><SeverityPill severity={severityFor(policy.risk)} label={`${policy.risk} risk`} /></View><Text style={styles.policyBody}>{policy.description}</Text><View style={styles.policyFoot}><Text style={styles.policyFootText}>{policy.autoExecute ? "Auto-execute in policy band" : `Authority: ${policy.requiredRoles.join(" + ")}`}</Text><Icon name={policy.autoExecute ? "bolt" : "lock"} color={policy.autoExecute ? "#21D4C2" : "#F5B84B"} size={16} /></View></Surface>)}</View>
  <SectionTitle eyebrow="Governance invariants" title="Every action is traceable" /><View style={styles.invariants}><Invariant icon="policy" title="Deterministic rules" text="Rules handle known thresholds; AI is reserved for interpretation and uncertainty." /><Invariant icon="fact-check" title="Evidence states" text="Verified, likely, estimated, and unknown claims remain visually distinct." /><Invariant icon="receipt-long" title="Audit memory" text="Requests, approvals, execution, and verification create durable operational records." /></View><View style={{ height: 28 }} />
</ScrollView></ScreenContainer>; }
function Invariant({ icon, title, text }: { icon: "policy" | "fact-check" | "receipt-long"; title: string; text: string }) { return <Surface style={styles.invariant}><Icon name={icon} color="#4E9BFF" size={19} /><View style={{ flex: 1 }}><Text style={styles.invariantTitle}>{title}</Text><Text style={styles.invariantText}>{text}</Text></View></Surface>; }
const styles = StyleSheet.create({ content: { gap: 15, paddingHorizontal: 18, paddingTop: 10 }, header: { alignItems: "center", flexDirection: "row", gap: 10 }, icon: { alignItems: "center", backgroundColor: "#183536", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, eyebrow: { color: "#8EA0A7", fontSize: 10, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, title: { color: "#E8F0F1", fontSize: 29, fontWeight: "900", letterSpacing: -0.9 }, headerCard: { gap: 8, padding: 15 }, headerTitle: { color: "#DCE8EA", fontSize: 15, fontWeight: "800", lineHeight: 20 }, headerBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18 }, policies: { gap: 9 }, policy: { gap: 10, padding: 14 }, policyTop: { alignItems: "flex-start", flexDirection: "row", gap: 10 }, policyTitle: { color: "#E1EBED", fontSize: 14, fontWeight: "800" }, policyId: { color: "#789098", fontSize: 10, fontWeight: "800", marginTop: 3 }, policyBody: { color: "#A6B9BD", fontSize: 12, lineHeight: 17 }, policyFoot: { alignItems: "center", backgroundColor: "#17242A", borderRadius: 10, flexDirection: "row", justifyContent: "space-between", padding: 10 }, policyFootText: { color: "#B8CACC", fontSize: 11, fontWeight: "700" }, invariants: { gap: 9 }, invariant: { alignItems: "flex-start", flexDirection: "row", gap: 10, padding: 13 }, invariantTitle: { color: "#DCE8EA", fontSize: 13, fontWeight: "800" }, invariantText: { color: "#9FB2B7", fontSize: 11, lineHeight: 16, marginTop: 3 } });
