import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { Icon, LinkedRecord, SectionTitle, SeverityPill, Surface } from "@/components/atlas-ui";
import { ScreenContainer } from "@/components/screen-container";
import { causalLinks, industrialMemory } from "@/lib/atlas-advanced";

export default function MemoryScreen() { return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.header}><View style={styles.icon}><Icon name="memory" color="#21D4C2" size={21} /></View><View><Text style={styles.eyebrow}>Institutional memory</Text><Text style={styles.title}>Learn from reality</Text></View></View>
  <Surface style={styles.principle}><Text style={styles.principleTitle}>Event → Decision → Outcome → Lesson</Text><Text style={styles.principleBody}>Atlas retains the operating context and evidence state so future recommendations can distinguish verified learning from a provisional interpretation.</Text></Surface>
  <SectionTitle eyebrow="Causal chain" title="Why this matters" />
  {causalLinks.map((chain) => <Surface key={chain.id} style={styles.chain}><Row label="Observed" text={chain.observation} color="#4E9BFF" /><Row label="Likely contributor" text={chain.contributor} color="#F5B84B" /><Row label="Probable cause" text={chain.cause} color="#FF6B57" /><Row label="Verification" text={chain.verification} color="#21D4C2" /><SeverityPill severity={chain.evidenceState === "likely" ? "attention" : "good"} label={chain.evidenceState} /></Surface>)}
  <SectionTitle eyebrow="Recorded cycles" title="Decision history" />
  <View style={styles.records}>{industrialMemory.map((entry) => <LinkedRecord key={entry.id} icon="history" title={entry.event} detail={`${entry.timestamp} · ${entry.owner}`} onPress={() => router.push({ pathname: "/twin/[id]", params: { id: entry.linkedAssetId ?? "MX-14" } })} />)}</View>
  {industrialMemory.map((entry) => <Surface key={`${entry.id}-lesson`} style={styles.lesson}><Text style={styles.lessonLabel}>LESSON · {entry.evidenceState}</Text><Text style={styles.lessonText}>{entry.lesson}</Text><Text style={styles.outcome}>{entry.outcome}</Text></Surface>)}<View style={{ height: 28 }} />
</ScrollView></ScreenContainer>; }
function Row({ label, text, color }: { label: string; text: string; color: string }) { return <View style={styles.row}><View style={[styles.rowLine, { backgroundColor: color }]} /><View style={styles.rowCopy}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowText}>{text}</Text></View></View>; }
const styles = StyleSheet.create({ content: { gap: 15, paddingHorizontal: 18, paddingTop: 10 }, header: { alignItems: "center", flexDirection: "row", gap: 10 }, icon: { alignItems: "center", backgroundColor: "#183536", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, eyebrow: { color: "#8EA0A7", fontSize: 10, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, title: { color: "#E8F0F1", fontSize: 29, fontWeight: "900", letterSpacing: -0.9 }, principle: { gap: 8, padding: 15 }, principleTitle: { color: "#DCE8EA", fontSize: 15, fontWeight: "800" }, principleBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18 }, chain: { gap: 10, padding: 14 }, row: { flexDirection: "row", gap: 10 }, rowLine: { borderRadius: 2, width: 4 }, rowCopy: { flex: 1, gap: 3 }, rowLabel: { color: "#8BA2A8", fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, rowText: { color: "#C4D4D7", fontSize: 12, lineHeight: 17 }, records: { gap: 9 }, lesson: { gap: 6, padding: 14 }, lessonLabel: { color: "#75E8DA", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, lessonText: { color: "#E1EBED", fontSize: 13, fontWeight: "700", lineHeight: 18 }, outcome: { color: "#8EA0A7", fontSize: 11, lineHeight: 16 } });
