import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { Icon, LinkedRecord, MetricCard, PrimaryButton, SectionTitle, SeverityPill, Surface } from "@/components/atlas-ui";
import { ScreenContainer } from "@/components/screen-container";
import { activeNetworkDemand, activeNetworkTransaction, capacityOffers, networkMatches, networkParticipants, resilienceSignals } from "@/lib/atlas-network";
import { useAtlas } from "@/lib/atlas-store";
import type { AtlasMatchObjective } from "@/shared/atlas-domain";

const objectives: { id: AtlasMatchObjective; label: string }[] = [{ id: "best_overall", label: "Best overall" }, { id: "lowest_cost", label: "Lowest cost" }, { id: "fastest", label: "Fastest" }, { id: "most_resilient", label: "Resilient" }];
const severityFor = (state: string) => state === "at_risk" ? "high" : state === "watch" ? "attention" : "good" as const;

export default function NetworkScreen() {
  const [objective, setObjective] = useState<AtlasMatchObjective>("best_overall");
  const { notify } = useAtlas();
  const matches = useMemo(() => networkMatches(objective), [objective]);
  const top = matches[0];
  const partner = top ? networkParticipants.find((record) => record.id === top.participantId) : undefined;
  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={styles.icon}><Icon name="public" color="#21D4C2" size={21} /></View><View><Text style={styles.eyebrow}>Atlas industrial network</Text><Text style={styles.title}>Coordinate capacity</Text></View></View>
    <Surface style={styles.networkState}><View style={styles.stateTop}><View><Text style={styles.stateLabel}>NETWORK PARTICIPATION</Text><Text style={styles.stateTitle}>Private operating data stays private</Text></View><SeverityPill severity="good" label="Sharing governed" /></View><Text style={styles.stateBody}>Capacity, capability, certificates, and transaction readiness are shared only at their configured visibility level. Raw machine data and restricted operating records are never exposed through matching.</Text></Surface>
    <View style={styles.metrics}><MetricCard label="Visible capacity" value="248 h" detail="Across governed offers" icon="precision-manufacturing" tone="good" /><MetricCard label="Qualified partners" value="4" detail="Evidence-aware profiles" icon="verified" tone="neutral" /></View>
    <SectionTitle eyebrow="Demand → capacity" title="Network match" />
    <Surface style={styles.demand}><Text style={styles.demandLabel}>OPEN DEMAND</Text><Text style={styles.demandTitle}>{activeNetworkDemand.title}</Text><Text style={styles.demandBody}>{activeNetworkDemand.requiredHours} hours · {activeNetworkDemand.requiredCapability} · {activeNetworkDemand.dueInDays}-day delivery window · {activeNetworkDemand.requiredCertification} required</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.objectives}>{objectives.map((item) => <Pressable key={item.id} onPress={() => setObjective(item.id)} style={[styles.objective, objective === item.id && styles.objectiveActive]}><Text style={[styles.objectiveText, objective === item.id && styles.objectiveTextActive]}>{item.label}</Text></Pressable>)}</ScrollView>{top && partner ? <View style={styles.match}><View style={styles.matchBadge}><Text style={styles.matchScore}>{top.score}</Text><Text style={styles.matchScoreLabel}>MATCH</Text></View><View style={{ flex: 1 }}><Text style={styles.matchTitle}>{partner.name}</Text><Text style={styles.matchBody}>{top.explanation[0]} · {top.explanation[1]}</Text><Text style={styles.matchEvidence}>Evidence state: {top.evidenceState}</Text></View></View> : <Text style={styles.noMatch}>No visible offer currently satisfies the selected constraints.</Text>}<PrimaryButton label="Prepare governed match request" icon="verified" onPress={() => notify("This local ranking is ready for review. Live match requests require migrated network participants and role-scoped approvals.", "warning")} /></Surface>
    <SectionTitle eyebrow="Capacity market" title="Available capability" />
    <View style={styles.records}>{capacityOffers.map((offer) => { const owner = networkParticipants.find((record) => record.id === offer.participantId); return <LinkedRecord key={offer.id} icon="precision-manufacturing" title={`${offer.capability} · ${offer.availableHours} h`} detail={`${owner?.name ?? "Network participant"} · ${offer.leadTimeDays}-day lead · ${offer.visibility} visibility`} severity={offer.reliabilityScore >= 95 ? "good" : "attention"} onPress={() => router.push({ pathname: "/partner/[id]", params: { id: offer.participantId } })} />; })}</View>
    <SectionTitle eyebrow="Network trust" title="Verified participants" />
    <View style={styles.records}>{networkParticipants.map((participant) => <LinkedRecord key={participant.id} icon="business" title={participant.name} detail={`${participant.kind.replace("_", " ")} · delivery ${participant.deliveryReliability}% · quality ${participant.qualityScore}%`} severity={participant.trustState === "verified" ? "good" : "attention"} onPress={() => router.push({ pathname: "/partner/[id]", params: { id: participant.id } })} />)}</View>
    <SectionTitle eyebrow="Resilience engine" title="Dependencies to watch" />
    <View style={styles.records}>{resilienceSignals.map((signal) => <LinkedRecord key={signal.title} icon="warning-amber" title={signal.title} detail={`${signal.alternativePath} · Recovery ${signal.recoveryTime}`} severity={severityFor(signal.state)} onPress={() => router.push("/scenario")} />)}</View>
    <SectionTitle eyebrow="Transaction readiness" title="Evidence before settlement" />
    <Surface style={styles.transaction}><View><Text style={styles.transactionTitle}>{activeNetworkTransaction.title}</Text><Text style={styles.transactionBody}>Current stage: {activeNetworkTransaction.stage}. Production, inspection, shipment, and delivery must be evidenced before the transaction can progress.</Text></View><PrimaryButton label="Inspect transaction path" kind="secondary" icon="receipt-long" onPress={() => router.push("/network-transaction")} /></Surface><View style={{ height: 32 }} />
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 15, paddingHorizontal: 18, paddingTop: 10 }, header: { alignItems: "center", flexDirection: "row", gap: 10 }, icon: { alignItems: "center", backgroundColor: "#183536", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, eyebrow: { color: "#8EA0A7", fontSize: 10, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, title: { color: "#E8F0F1", fontSize: 29, fontWeight: "900", letterSpacing: -0.9 }, networkState: { gap: 9, padding: 15 }, stateTop: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, stateLabel: { color: "#8EA0A7", fontSize: 9, fontWeight: "900", letterSpacing: 0.9 }, stateTitle: { color: "#E2ECEE", fontSize: 15, fontWeight: "800", marginTop: 3 }, stateBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18 }, metrics: { flexDirection: "row", gap: 10 }, demand: { gap: 12, padding: 15 }, demandLabel: { color: "#79B7FF", fontSize: 10, fontWeight: "900", letterSpacing: 0.9 }, demandTitle: { color: "#E5EFF0", fontSize: 17, fontWeight: "900" }, demandBody: { color: "#AABCC0", fontSize: 12, lineHeight: 17 }, objectives: { gap: 8 }, objective: { borderColor: "#33474E", borderRadius: 99, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 }, objectiveActive: { backgroundColor: "#1B4543", borderColor: "#21D4C2" }, objectiveText: { color: "#A4B7BB", fontSize: 11, fontWeight: "800" }, objectiveTextActive: { color: "#7CE5D4" }, match: { alignItems: "center", backgroundColor: "#17242A", borderRadius: 13, flexDirection: "row", gap: 11, padding: 12 }, matchBadge: { alignItems: "center", backgroundColor: "#1B4543", borderRadius: 13, height: 54, justifyContent: "center", width: 54 }, matchScore: { color: "#7CE5D4", fontSize: 19, fontWeight: "900" }, matchScoreLabel: { color: "#8FCCC4", fontSize: 8, fontWeight: "900", letterSpacing: 0.6 }, matchTitle: { color: "#E0EAEC", fontSize: 13, fontWeight: "800" }, matchBody: { color: "#9FB2B7", fontSize: 11, lineHeight: 16, marginTop: 3 }, matchEvidence: { color: "#7FB8FF", fontSize: 10, fontWeight: "800", marginTop: 4 }, noMatch: { color: "#F5B84B", fontSize: 12, fontWeight: "700" }, records: { gap: 9 }, transaction: { gap: 12, padding: 15 }, transactionTitle: { color: "#E1EBED", fontSize: 15, fontWeight: "800" }, transactionBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18, marginTop: 5 } });
