import { ScrollView, StyleSheet, Text, View } from "react-native";

import { Icon, SectionTitle, SeverityPill, Surface } from "@/components/atlas-ui";
import { ScreenContainer } from "@/components/screen-container";
import { activeNetworkTransaction } from "@/lib/atlas-network";

const stages = ["demand", "offer", "authorization", "production", "inspection", "shipment", "delivery", "invoice", "settlement"] as const;
export default function NetworkTransactionScreen() { const activeIndex = stages.indexOf(activeNetworkTransaction.stage); return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.header}><View style={styles.icon}><Icon name="receipt-long" color="#21D4C2" size={21} /></View><View><Text style={styles.eyebrow}>Transaction readiness</Text><Text style={styles.title}>{activeNetworkTransaction.title}</Text></View></View>
  <Surface style={styles.context}><Text style={styles.contextTitle}>Evidence before settlement</Text><Text style={styles.contextBody}>Atlas preserves the operational proof chain. It prepares transaction readiness; regulated settlement, escrow, lending, insurance, and legal commitments require separately approved partners and controls.</Text><SeverityPill severity="attention" label="Authorization pending" /></Surface>
  <SectionTitle eyebrow="Digital thread" title="Transaction path" /><View style={styles.stages}>{stages.map((stage, index) => { const complete = index < activeIndex; const current = index === activeIndex; return <View key={stage} style={styles.stageRow}><View style={[styles.dot, complete && styles.dotComplete, current && styles.dotCurrent]}><Icon name={complete ? "check" : current ? "hourglass-top" : "lock"} size={14} color={complete ? "#071416" : current ? "#F5B84B" : "#62777E"} /></View><View style={styles.stageCopy}><Text style={styles.stageName}>{stage}</Text><Text style={styles.stageText}>{complete ? "Evidence retained" : current ? "Current controlled gate" : "Blocked until predecessor evidence is verified"}</Text></View></View>; })}</View>
  <SectionTitle eyebrow="Audit requirement" title="Proof of occurrence" /><Surface style={styles.audit}><Text style={styles.auditText}>Every stage must record who acted, what was observed, what evidence was used, who authorized the next action, and what outcome followed. This path is intentionally not a payment processor.</Text></Surface><View style={{ height: 30 }} />
</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 15, paddingHorizontal: 18, paddingTop: 10 }, header: { alignItems: "center", flexDirection: "row", gap: 10 }, icon: { alignItems: "center", backgroundColor: "#183536", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, eyebrow: { color: "#8EA0A7", fontSize: 10, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, title: { color: "#E8F0F1", fontSize: 24, fontWeight: "900", letterSpacing: -0.6 }, context: { gap: 8, padding: 15 }, contextTitle: { color: "#E1EBED", fontSize: 15, fontWeight: "800" }, contextBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18 }, stages: { gap: 0 }, stageRow: { flexDirection: "row", gap: 11, minHeight: 62 }, dot: { alignItems: "center", backgroundColor: "#263238", borderRadius: 14, height: 28, justifyContent: "center", width: 28 }, dotComplete: { backgroundColor: "#21D4C2" }, dotCurrent: { backgroundColor: "#3A2C16" }, stageCopy: { borderBottomColor: "#28383E", borderBottomWidth: 1, flex: 1, paddingBottom: 13 }, stageName: { color: "#E1EBED", fontSize: 13, fontWeight: "800", textTransform: "capitalize" }, stageText: { color: "#8FA5AA", fontSize: 11, lineHeight: 16, marginTop: 3 }, audit: { padding: 15 }, auditText: { color: "#AABCC0", fontSize: 12, lineHeight: 18 } });
