import { router, useLocalSearchParams } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { Icon, LinkedRecord, PrimaryButton, SectionTitle, SeverityPill, Surface } from "@/components/atlas-ui";
import { ScreenContainer } from "@/components/screen-container";
import { capacityOffers, networkParticipants } from "@/lib/atlas-network";

export default function PartnerScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const partner = networkParticipants.find((entry) => entry.id === id) ?? networkParticipants[0];
  const offers = capacityOffers.filter((offer) => offer.participantId === partner.id);
  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={styles.icon}><Icon name="business" color="#21D4C2" size={21} /></View><View style={{ flex: 1 }}><Text style={styles.eyebrow}>Industrial partner profile</Text><Text style={styles.title}>{partner.name}</Text><Text style={styles.sub}>{partner.region} · {partner.kind.replace("_", " ")}</Text></View><SeverityPill severity={partner.trustState === "verified" ? "good" : "attention"} label={partner.trustState} /></View>
    <Surface style={styles.trust}><Text style={styles.trustLabel}>EVIDENCE-BASED TRUST</Text><View style={styles.scores}><Score value={`${partner.deliveryReliability}%`} label="Delivery" /><Score value={`${partner.qualityScore}%`} label="Quality" /><Score value={partner.visibility} label="Sharing" /></View><Text style={styles.trustBody}>Trust is derived from verified identity, certificates, authorized operational evidence, and performance history. It is not a consumer-style rating.</Text></Surface>
    <SectionTitle eyebrow="Visible capability" title="Capacity offers" /><View style={styles.records}>{offers.map((offer) => <LinkedRecord key={offer.id} icon="precision-manufacturing" title={`${offer.capability} · ${offer.availableHours} h`} detail={`${offer.leadTimeDays}-day lead · ${offer.certifications.join(", ")} · ${offer.visibility}`} severity={offer.qualityScore >= 94 ? "good" : "attention"} />)}</View>
    <SectionTitle eyebrow="Network transaction" title="Engagement boundary" /><Surface style={styles.boundary}><Text style={styles.boundaryTitle}>No binding commitment is made here.</Text><Text style={styles.boundaryBody}>A capacity match creates an auditable request. Pricing, contract terms, delivery obligations, and settlement remain subject to the partner’s authorized commercial workflow.</Text><PrimaryButton label="Return to network exchange" kind="secondary" icon="arrow-back" onPress={() => router.back()} /></Surface><View style={{ height: 30 }} />
  </ScrollView></ScreenContainer>;
}
function Score({ value, label }: { value: string; label: string }) { return <View style={styles.score}><Text style={styles.scoreValue}>{value}</Text><Text style={styles.scoreLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: 15, paddingHorizontal: 18, paddingTop: 10 }, header: { alignItems: "center", flexDirection: "row", gap: 10 }, icon: { alignItems: "center", backgroundColor: "#183536", borderRadius: 14, height: 44, justifyContent: "center", width: 44 }, eyebrow: { color: "#8EA0A7", fontSize: 10, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, title: { color: "#E8F0F1", fontSize: 22, fontWeight: "900", letterSpacing: -0.6 }, sub: { color: "#8EA0A7", fontSize: 11, fontWeight: "700", marginTop: 2 }, trust: { gap: 12, padding: 15 }, trustLabel: { color: "#21D4C2", fontSize: 10, fontWeight: "900", letterSpacing: 0.9 }, scores: { flexDirection: "row", gap: 8 }, score: { backgroundColor: "#17242A", borderRadius: 11, flex: 1, padding: 10 }, scoreValue: { color: "#E1EBED", fontSize: 14, fontWeight: "900" }, scoreLabel: { color: "#8EA0A7", fontSize: 9, fontWeight: "800", marginTop: 3, textTransform: "uppercase" }, trustBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18 }, records: { gap: 9 }, boundary: { gap: 9, padding: 15 }, boundaryTitle: { color: "#E1EBED", fontSize: 14, fontWeight: "800" }, boundaryBody: { color: "#9FB2B7", fontSize: 12, lineHeight: 18 } });
